### ISSUE TITLE
Rename everything to Test -> Experiment -> Trials

### ISSUE THREAD

**Issue by simonedavico** [benchflow/client#22]
This issue is a continuation of [issue #48 from drivers-maker](https://github.com/benchflow/drivers-maker/issues/48).

We should refactor all instances of `benchflowBenchmark`, `benchmark` to use the correct naming (either `test` or `experiment`, depending on the context of the command).

**Comment by VincenzoFerme** [comment]
This issue was moved to benchflow/benchflow#316
