### ISSUE TITLE
Client Should be Configurable Using an Hidden Configuration File

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/client#23]
Let the client be configurable using an hidden configuration file, in a specific directory. 

In the current version of the client, we just add a configuration command, that ask the user to input the expected configuration (that now it is expressed using environment variables: https://github.com/benchflow/client/blob/dev/benchflow.py#L9), and store them in this file that then it is used as reference for configuration (and probably needs to be copied or shared as volume in the container in the same path as it is stored in the host, so the containerised client can read, and potentially update, it).

References: http://superuser.com/a/631984

**Comment by simonedavico** [comment]
So `benchflow` is installed under `/etc/opt`?

*----------------------------------------*
*Simone D'Avico*
*Master Student*
*Faculty of Informatics*
*Università della Svizzera Italiana*
*simonedavico.github.io <http://simonedavico.github.io>*
atelier.inf.usi.ch/~davicos

2016-08-22 17:55 GMT+02:00 Vincenzo Ferme <notifications@github.com>:

**Comment by VincenzoFerme** [comment]
Since benchflow is installed in [/usr/local/bin](https://github.com/benchflow/collectors/issues/85), the configuration file should be placed in the user's home folder.

**Comment by VincenzoFerme** [comment]
This issue was moved to benchflow/benchflow#317
